version: '3.5'

services:

  web:
    build:
      context: sleepless
      dockerfile: Dockerfile
    image: web
    container_name: web
    ports:
      - '8000:8000'
    volumes:
      - './sleepless:/usr/src/app'
      - './data:/var/data'
    command: gunicorn -b 0.0.0.0:8000 app.wsgi:app